version: '3.8'

services:
  oracle-db:
    image: vulpes94/oracle:19.3.0-ee-slim
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=1234
      - ORACLE_CHARACTERSET=AL32UTF
    volumes:
      - ./app/init.sql:/container-entrypoint-initdb.d/init.sql:ro
    restart: always

  tomcat-app:
    build: ./
    container_name: tomcat-spring
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    restart: always
